version: "2.2" # TODO: change to version 3?
services:
  postgres:
    image: mdillon/postgis:11
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_development
