enum AUTH_ACTIONS {
  LOGIN = 'LOGIN',
  VERIFY_CREDENTIALS = 'VERIFY_CREDENTIALS',
  ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
}

export default AUTH_ACTIONS;
