enum EMPLOYEES_ACTION {
  GET_EMPLOYEES_LIST = 'GET_EMPLOYEES_LIST',
  GET_CAREER_DAYS = 'GET_CAREER_DAYS',
  GET_SELECTED_EMPLOYEE = 'GET_SELECTED_EMPLOYEE',
  GET_SELECTED_CAREER_DAY = 'GET_SELECTED_CAREER_DAY',
  ADD_CAREER_DAY = 'ADD_CAREER_DAY',
  ADD_OBJECTIVE = 'ADD_OBJECTIVE',
  DELETE_CAREER_DAY = 'DELETE_CAREER_DAY',
}

export default EMPLOYEES_ACTION;
